cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_product_view, name='cart_remove'),
    path('clear/', views.clear_cart_view, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('search/', include('search.urls', namespace='search')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:product_pk>/<str:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/comment/<int:product_pk>/', views.ProductCommentView.as_view(), name='product_comment'),
    path('product/like/<int:product_pk>/', views.ProductLikeView.as_view(), name='product_like'),
    path('product/dislike/<int:product_pk>/', views.ProductDislikeView.as_view(), name='product_dislike'),
    path('category/<int:category_pk>/', views.CategoryListView.as_view(), name='category_list'),
]

cart/forms.py
from django import forms



class AddToCartForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.utils.translation import gettext as _

from products.models import Product
from .cart import Cart
from .forms import AddToCartForm


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['replace_quantity_form'] = AddToCartForm(
            initial={
                'quantity': item['quantity'],
                'inplace': True
            }
        )

    return render(request, 'cart/cart.html', {
        'cart': cart,
    })


def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        inplace = cleaned_data['inplace']
        cart.add(product, quantity, inplace)

    messages.success(request, _('your product added to cart successfully !'))
    return redirect(request.META.get('HTTP_REFERER'))


def remove_product_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, _('your product removed from cart successfully !'))
    return redirect(request.META.get('HTTP_REFERER', 'cart:cart_detail'))


def clear_cart_view(request):
    cart = Cart(request)
    if len(cart):
        cart.clear()
        messages.success(request, _('Now your cart is empty.'))
        return redirect('products:product_list')
    messages.error(request, _('Nothing to clear!'))
    return redirect('products:product_list')

cart/templates/cart/cart.html
{% extends '-base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% translate 'Cart' %}
{% endblock %}


{% block context %}
    <div class="breadcrumb-area bg-gray">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <ul>
                    <li>
                        <a href="{% url 'products:product_list' %}">{% trans 'Home' %}</a>
                    </li>
                    <li class="active">Cart Page</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="cart-main-area pt-115 pb-120">
        <div class="container">
            <h3 class="cart-page-title">Your cart items</h3>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <form action="#">
                        <div class="table-content table-responsive cart-table-content">
                            {% if cart|length %}
                                <table>
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Product Name</th>
                                        <th>Until Price</th>
                                        <th>Qty</th>
                                        <th>Subtotal</th>
                                        <th>action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in cart %}
                                            <tr>
                                            <td class="product-thumbnail">
                                                <a href="{{item.product_obj.get_absolute_url}}"><img src="{{item.product_obj.main_cover.url}}" alt=""></a>
                                            </td>
                                            <td class="product-name"><a href="{{item.product_obj.get_absolute_url}}">{{ item.product_obj.title}}</a></td>
                                            <td class="product-price-cart"><span class="amount">${{ item.total_price }}</span></td>
                                            <td class="product-quantity pro-details-quality">
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" type="text" name="qtybutton" value="{{ item.quantity }}">
                                                </div>
                                            </td>
                                            <td class="product-subtotal">${{ item.product_obj.total_price }}</td>
                                            <td class="product-remove">
                                                <a href="{% url 'cart:cart_remove' item.product_obj.id %}"><i class="icon_close"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                {% trans 'Your cart is empty, Continue shopping first!' %}
                            {% endif %}
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="cart-shiping-update-wrapper">
                                    <div class="cart-shiping-update">
                                        <a href="{% url "products:product_list" %}">Continue Shopping</a>
                                    </div>
                                    <div class="cart-clear">
                                        <button>Update Cart</button>
                                        {% if cart|length  %}
                                            <a href="{% url 'cart:cart_clear' %}">Clear Cart</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}