accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('changepassword/', views.ChangePassword.as_view(), name='change_password'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_product_view, name='cart_remove'),
    path('clear/', views.clear_cart_view, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('search/', include('search.urls', namespace='search')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.OrderView.as_view(), name='order'),
    path('detail/<int:order_pk>/', views.OrderDetailsView.as_view(), name='order_detail'),
    path('clear/<int:order_pk>/', views.ClearOrderView.as_view(), name='order_clear'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:product_pk>/<str:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/comment/<int:product_pk>/', views.ProductCommentView.as_view(), name='product_comment'),
    path('product/like/<int:product_pk>/', views.ProductLikeView.as_view(), name='product_like'),
    path('product/dislike/<int:product_pk>/', views.ProductDislikeView.as_view(), name='product_dislike'),
    path('category/<int:category_pk>/', views.CategoryListView.as_view(), name='category_list'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator
from django.db import models


class CustomUser(AbstractUser):
    phone_number = models.CharField(validators=[MinLengthValidator(11)], max_length=11, blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    pass


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, Value
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.views import View
from django.contrib.auth.forms import PasswordChangeForm

from .forms import CustomUserChangeForm


class ProfileView(LoginRequiredMixin, View):
    form_class = CustomUserChangeForm

    def get(self, request):
        user = request.user
        userprofile_form = self.form_class(instance=request.user)
        userpassword_form = PasswordChangeForm(request.user)
        orders = user.orders.prefetch_related('items').annotate(price=Sum(F('items__quantity') * F('items__price'))).all()
        return render(request, 'accounts/profile.html',
                      {'user': user, 'userprofile_form': userprofile_form, 'userpassword_form': userpassword_form, 'orders': orders})

    def post(self, request):
        userprofile_form = self.form_class(request.POST, instance=request.user)
        if userprofile_form.is_valid():
            user = userprofile_form.save(commit=False)
            user.is_active = True
            user.save()
            messages.success(request, _('You Change your profile successfully!'), 'success')
            return redirect('accounts:profile')
        messages.error(request, userprofile_form.errors, 'danger')
        return redirect('accounts:profile')


class ChangePassword(LoginRequiredMixin, View):
    def Post(self, request):
        userpassword_form = PasswordChangeForm(request.user, request.POST)
        if userpassword_form.is_valid():
            userpassword_form.save()
            messages.success(request, _('You Change your profile successfully!'), 'success')
            return redirect('accounts:profile')
        messages.error(request, userpassword_form.errors, 'danger')
        print(userpassword_form.errors)
        return redirect('accounts:profile')

accounts/templates/accounts/profile.html
{% extends '-base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}
    {% translate 'Profile' %}
{% endblock %}

{% block context %}
    <div class="breadcrumb-area bg-gray">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <ul>
                    <li>
                        <a href="{% url 'products:product_list' %}">{% trans 'Home' %}</a>
                    </li>
                    <li class="active">{% trans 'my account' %}</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- my account wrapper start -->
    <div class="my-account-wrapper pt-120 pb-120">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- My Account Page Start -->
                    <div class="myaccount-page-wrapper">
                        <!-- My Account Tab Menu Start -->
                        <div class="row">
                            <div class="col-lg-3 col-md-4">
                                <div class="myaccount-tab-menu nav" role="tablist">
                                    <a href="#dashboad" data-toggle="tab" class="active"><i class="fa fa-dashboard"></i>
                                        {% trans 'Dashboard' %}</a>
                                    <a href="#account-info" data-toggle="tab"><i
                                            class="fa fa-user"></i> {% trans 'Account Details' %}</a>
                                    <a href="#orders" data-toggle="tab"><i
                                            class="fa fa-cart-arrow-down"></i> {% trans 'Orders' %}</a>
                                    <a href="{% url 'account_logout' %}"><i
                                            class="fa fa-sign-out"></i> {% trans 'Logout' %}</a>
                                </div>
                            </div>
                            <!-- My Account Tab Menu End -->
                            <!-- My Account Tab Content Start -->
                            <div class="col-lg-9 col-md-8">
                                <div class="tab-content" id="myaccountContent">
                                    <!-- Single Tab Content Start -->
                                    <div class="tab-pane fade show active" id="dashboad" role="tabpanel">
                                        <div class="myaccount-content">
                                            <h3>{% trans 'Dashboard' %}</h3>
                                            <div class="welcome">
                                                <p>{% trans 'Hello,' %} <strong>{{ user.username }}</strong></p>
                                            </div>

                                            <p class="mb-0">
                                                {% trans 'From your account dashboard. you can easily check & view your recent orders, manage your shipping and billing and edit your password and account details.' %}
                                            </p>
                                        </div>
                                    </div>
                                    <!-- Single Tab Content End -->
                                    <!-- Single Tab Content Start -->
                                    <div class="tab-pane fade" id="account-info" role="tabpanel">
                                        <div class="myaccount-content">
                                            <h3>{% trans 'Account Details' %}</h3>
                                            <div class="account-details-form">
                                                <form action="{% url 'accounts:profile' %}" method="post"
                                                      autocomplete="off">
                                                    {% csrf_token %}
                                                    {{ userprofile_form.non_field_errors | safe }}
                                                    <div class="single-input-item">
                                                        {{ userprofile_form.username.errors | safe }}
                                                        <label for="display-name"
                                                               class="required">{% trans 'Username' %}</label>
                                                        {% render_field userprofile_form.username name='username' type="text" id="display-name" %}
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="single-input-item">
                                                                {{ userprofile_form.first_name.errors | safe }}
                                                                <label for="first-name"
                                                                       class="required">{% trans 'First Name' %}</label>
                                                                {% render_field userprofile_form.first_name name='first_name' type="text" id="first-name" %}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="single-input-item">
                                                                {{ userprofile_form.last_name.errors | safe }}
                                                                <label for="last-name"
                                                                       class="required">{% trans 'last name' %}</label>
                                                                {% render_field userprofile_form.last_name name='last_name' type="text" id="last-name" %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="single-input-item">
                                                        {{ userprofile_form.email.errors | safe }}
                                                        <label for="email"
                                                               class="required">{% trans 'Email Address' %}</label>
                                                        {% render_field userprofile_form.email name='email' type="email" id="email" %}
                                                    </div>
                                                    <div class="single-input-item">
                                                        {{ userprofile_form.phone_number.errors | safe }}
                                                        <label for="email"
                                                               class="required">{% trans 'Phone Number' %}</label>
                                                        {% render_field userprofile_form.phone_number name='phone_number' type="phonenumber" id="phonenumber" %}
                                                    </div>
                                                    <div class="single-input-item">
                                                        <button type="submit"
                                                                class="check-btn sqr-btn ">{% trans 'Save Changes' %}</button>
                                                        <br>
                                                        <a href="{% url 'account_change_password' %}" class="check-btn sqr-btn "><i class="fa fa-edit"></i>
                                                            {% trans 'Edit Password' %}
                                                        </a>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div> <!-- Single Tab Content End -->
                                    <!-- Single Tab Content Start -->
                                    <div class="tab-pane fade" id="orders" role="tabpanel">
                                        <div class="myaccount-content">
                                            <h3>Orders</h3>
                                            <div class="myaccount-table table-responsive text-center">
                                                <table class="table table-bordered">
                                                    {% if orders %}
                                                        <thead class="thead-light">
                                                        <tr>
                                                            <th>{% translate 'Order' %}</th>
                                                            <th>{% translate 'Date' %}</th>
                                                            <th>{% translate 'Status' %}</th>
                                                            <th>{% translate 'Total Price' %}</th>
                                                            <th>{% translate 'Action' %}</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        {% for order in orders %}
                                                            <tr>
                                                                <td>{{ forloop.counter }}</td>
                                                                <td>{{ order.updated_on }}</td>
                                                                <td>Pending</td>
                                                                {% if orders.price %}
                                                                    <td>{% trans 'Toman' %} {{ order.price }}</td>
                                                                {% else %}
                                                                    <td>_</td>
                                                                {% endif %}
                                                                <td><a href="{% url 'order:order_detail' order.id %}" class="check-btn sqr-btn ">{% trans 'View' %}</a></td>
                                                            </tr>
                                                        {% endfor %}
                                                    {% else %}
                                                        <p>{% translate 'You have NO order' %}</p>
                                                    {% endif %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Single Tab Content End -->
                                </div>
                            </div> <!-- My Account Tab Content End -->
                        </div>
                    </div> <!-- My Account Page End -->
                </div>
            </div>
        </div>
    </div>
    <!-- my account wrapper end -->

{% endblock %}