cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_product_view, name='cart_remove'),
    path('clear/', views.clear_cart_view, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('search/', include('search.urls', namespace='search')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:product_pk>/<str:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/comment/<int:product_pk>/', views.ProductCommentView.as_view(), name='product_comment'),
    path('product/like/<int:product_pk>/', views.ProductLikeView.as_view(), name='product_like'),
    path('product/dislike/<int:product_pk>/', views.ProductDislikeView.as_view(), name='product_dislike'),
    path('category/<int:category_pk>/', views.CategoryListView.as_view(), name='category_list'),
]

search/urls.py
from django.urls import path
from . import views


app_name = 'search'
urlpatterns = [
    path('', views.SearchProducts.as_view(), name='search_products')
]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50)

search/views.py
from django.db.models import Prefetch
from django.shortcuts import render
from django.views import View
from products.models import Product
from .forms import SearchForm


class SearchProducts(View):
    def get(self, request):
        search = request.GET.get('search')
        products = Product.objects.prefetch_related('comments').filter(title__icontains=search, is_active=True)
        return render(request, 'search/searched_products.html', {'products': products})

search/templates/search/searched_products.html
{% extends '-base.html' %}
{% load tags %}
{% load i18n %}

{% block title %}
    {% translate 'Search Result' %}
{% endblock %}

{% block context %}
    <div class="breadcrumb-area bg-gray">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <ul>
                    <li>
                        <a href="{% url 'products:product_list' %}">{% trans 'Home' %}</a>
                    </li>
                    <li class="active">{% trans 'Search Result' %} </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pt-120 pb-115">
        <div class="row">
            {% if products %}
                {% for product in products %}
                    {% if product.is_discount %}
                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="single-product-wrap mb-35">
                                <div class="product-img product-img-zoom mb-15">
                                    <a href="{% url 'products:product_detail' product.pk product.slug %}">
                                        <img src="{{ product.main_cover.url }}"
                                             alt="">
                                    </a>
                                    <span class="pro-badge left bg-red">-{{ product.discount_percent }}%</span>
                                    <div class="product-action-2 tooltip-style-2">
                                        <button title="Wishlist"><i class="icon-heart"></i></button>
                                        <button title="Quick View" data-toggle="modal"
                                                data-target="{{ product.get_absolute_url }}">
                                            <i class="icon-size-fullscreen icons"></i></button>
                                        <button title="Compare"><i class="icon-refresh"></i></button>
                                    </div>
                                </div>
                                <div class="product-content-wrap-2 text-center">
                                    {% if product.average_rate > 0 %}
                                        <div class="product-rating-wrap">
                                            <div class="product-rating">
                                                {% if product.average_rate > 0 %}
                                                    <i class="icon_star"></i>
                                                {% endif %}
                                                {% if product.average_rate > 1 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 2 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 3 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 4 %}
                                                    <i class="icon_star"></i>
                                                {% endif %}
                                            </div>
                                            <span>({{ product.comments.all|length }})</span>
                                        </div>
                                    {% endif %}
                                    <h3>
                                        <a href="{% url 'products:product_detail' product.pk product.slug %}">{{ product.title }}</a>
                                    </h3>
                                    <div class="product-price-2">
                                        <span class="new-price">{% trans 'Toman' %}{{ product.total_price }}</span>
                                        <span class="old-price">{% trans 'Toman' %}{{ product.og_price }}</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap-2 product-content-position text-center">
                                    {% if product.average_rate > 0 %}
                                        <div class="product-rating-wrap">
                                            <div class="product-rating">
                                                {% if product.average_rate > 0 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 1 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 2 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 3 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 4 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                            </div>
                                            <span>({{ product.comments.all|length }})</span>
                                        </div>
                                    {% endif %}
                                    <h3>
                                        <a href="{% url 'products:product_detail' product.pk product.slug %}">{{ product.title }}</a>
                                    </h3>
                                    <div class="product-price-2">
                                        <span class="new-price">{% trans 'Toman' %}{{ product.og_price }}</span>
                                        <span class="old-price">{% trans 'Toman' %}{{ product.total_price }}</span>
                                    </div>
                                    <div class="pro-add-to-cart">
                                        <button title="Add to Cart">{% trans 'Add To Cart' %}</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="single-product-wrap mb-35">
                                <div class="product-img product-img-zoom mb-15">
                                    <a href="{% url 'products:product_detail' product.pk product.slug %}">
                                        <img src="{{ product.main_cover.url }}"
                                             alt="">
                                    </a>
                                    <div class="product-action-2 tooltip-style-2">
                                        <button title="Wishlist"><i class="icon-heart"></i></button>
                                        <button title="Quick View" data-toggle="modal"
                                                data-target="#exampleModal">
                                            <i class="icon-size-fullscreen icons"></i></button>
                                        <button title="Compare"><i class="icon-refresh"></i></button>
                                    </div>
                                </div>
                                <div class="product-content-wrap-2 text-center">
                                    {% if product.average_rate > 0 %}
                                        <div class="product-rating-wrap">
                                            <div class="product-rating">
                                                {% if product.average_rate > 0 %}
                                                    <i class="icon_star"></i>
                                                {% endif %}
                                                {% if product.average_rate > 1 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 2 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 3 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 4 %}
                                                    <i class="icon_star"></i>
                                                {% endif %}
                                            </div>
                                            <span>({{ product.comments.all|length }})</span>
                                        </div>
                                    {% endif %}
                                    <h3>
                                        <a href="{% url 'products:product_detail' product.pk product.slug %}">{{ product.title }}</a>
                                    </h3>
                                    <div class="product-price-2">
                                        <span>{% trans 'Toman' %}{{ product.total_price }}</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap-2 product-content-position text-center">
                                    {% if product.average_rate > 0 %}
                                        <div class="product-rating-wrap">
                                            <div class="product-rating">
                                                {% if product.average_rate > 0 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 1 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 2 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 3 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                                {% if product.average_rate > 4 %}
                                                    <i class="icon_star "></i>
                                                {% endif %}
                                            </div>
                                            <span>({{ product.comments.all|length }})</span>
                                        </div>
                                    {% endif %}
                                    <h3>
                                        <a href="{% url 'products:product_detail' product.pk product.slug %}">{{ product.title }}</a>
                                    </h3>
                                    <div class="product-price-2">
                                        <span>{% trans 'Toman' %}{{ product.total_price }}</span>
                                    </div>
                                    <div class="pro-add-to-cart">
                                        <button title="Add to Cart">{% trans 'Add To Cart' %}</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                {% endfor %}
            {% else %}
                <p>{% translate 'There is no result!' %}</p>
            {% endif %}
        </div>
    </div>

{% endblock %}