accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('changepassword/', views.ChangePassword.as_view(), name='change_password'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_product_view, name='cart_remove'),
    path('clear/', views.clear_cart_view, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('search/', include('search.urls', namespace='search')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.OrderView.as_view(), name='order'),
    path('detail/<int:order_pk>/', views.OrderDetailsView.as_view(), name='order_detail'),
    path('clear/<int:order_pk>/', views.ClearOrderView.as_view(), name='order_clear'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:product_pk>/<str:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/comment/<int:product_pk>/', views.ProductCommentView.as_view(), name='product_comment'),
    path('product/like/<int:product_pk>/', views.ProductLikeView.as_view(), name='product_like'),
    path('product/dislike/<int:product_pk>/', views.ProductDislikeView.as_view(), name='product_dislike'),
    path('category/<int:category_pk>/', views.CategoryListView.as_view(), name='category_list'),
]

search/urls.py
from django.urls import path
from . import views


app_name = 'search'
urlpatterns = [
    path('', views.SearchProducts.as_view(), name='search_products')
]

templates/inc/header.html
{% load widget_tweaks %}
{% load i18n %}
{% load static %}
<header class="header-area bg-white">
    <div class="header-large-device section-padding-2">
        <div class="header-top header-top-ptb-3 bg-black">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-12">

                    </div>
                </div>
            </div>
        </div>
        <div class="header-middle">
            <div class="container">
                <div class="border-bottom-1 header-top-ptb-4">
                    <div class="row align-items-center">
                        <div class="col-xl-4 col-lg-5">
                            <div class="search-wrap-2">
                                <form action="{% url 'search:search_products' %}" method="get">
                                    {% render_field search_form.search placeholder="عنوان را وارد کنید!" type="text" %}
                                    <button class="button-search"><i class="icon-magnifier"></i></button>
                                </form>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-2">
                            <div class="logo text-center">
                                <a href="index.html"><img src="{% static 'assets/images/logo/logo-2.png' %}" alt="logo"></a>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-5">
                            <div class="header-top-right">
                                {% if user.is_authenticated %}
                                    <div class="header-login-regi">
                                        <a href="{% url 'account_logout' %}"><i class="icon-user"></i> Logout </a>
                                    </div>
                                {% else %}
                                    <div>
                                        <a href="{% url 'account_login' %}"><i class="icon-user"></i> Log In</a>
                                    </div>
                                    <span> / </span>
                                    <div class="header-login-regi">
                                        <a href="{% url 'account_signup' %}">Register</a>
                                    </div>
                                {% endif %}
                                <div class="header-cart-2">
                                    <a class="cart-active" href="{% url 'cart:cart_detail' %}"><i class="icon-basket-loaded"></i> <span
                                            class="black">{{ cart|length }}</span> {{cart.get_total_price}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="main-menu main-menu-padding-2 main-menu-center main-menu-font-width-400 main-menu-lh-4 main-menu-hover-semibold main-menu-hover-border">
                            <nav>
                                <ul>
                                    <li><a class="active" href="{% url 'products:product_list' %}">{% translate 'HOME' %} </a>
                                    </li>
                                    <li><a href="#">{% trans 'PAGES' %} </a>
                                        <ul class="sub-menu-style">
                                            <li><a href="{% url 'accounts:profile' %}">{% trans 'my account' %}</a></li>
                                            <li><a href="wishlist.html">{% trans 'wishlist' %} </a></li>
                                            <li><a href="checkout.html">{% trans 'checkout' %} </a></li>
                                            <li><a href="contact.html">{% trans 'contact us' %} </a></li>
                                            <li><a href="order-tracking.html">{% trans 'order tracking' %}</a></li>
                                            <li><a href="login-register.html">{% trans 'login / register' %} </a></li>
                                        </ul>
                                    </li>
                                    <li><a href="contact.html">CONTACT </a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-small-device small-device-ptb-1">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-5">
                    <div class="mobile-logo">
                        <a href="index.html">
                            <img alt="" src="{% static 'images/logo/logo.png' %}">
                        </a>
                    </div>
                </div>
                <div class="col-7">
                    <div class="header-action header-action-flex">
                        <div class="same-style-2 same-style-2-font-inc">
                            <a href="login-register.html"><i class="icon-user"></i></a>
                        </div>
                        <div class="same-style-2 same-style-2-font-inc">
                            <a href="wishlist.html"><i class="icon-heart"></i><span
                                    class="pro-count black">03</span></a>
                        </div>
                        <div class="same-style-2 same-style-2-font-inc header-cart">
                            <a class="cart-active" href="#">
                                <i class="icon-basket-loaded"></i><span class="pro-count black">02</span>
                            </a>
                        </div>
                        <div class="same-style-2 main-menu-icon">
                            <a class="mobile-header-button-active" href="#"><i class="icon-menu"></i> </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/inc/message.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
        </button>
    </div>
{% endfor %}

templates/inc/mini_cart.html
{% load static %}
{% load i18n %}
<!-- mini cart start -->
<div class="sidebar-cart-active">
    <div class="sidebar-cart-all">
        <a class="cart-close" href="#"><i class="icon_close"></i></a>
        <div class="cart-content">
            <h3>{% trans 'Shopping Cart' %}</h3>
            <ul>
                {% for item in cart %}
                    <li class="single-product-cart">
                        <div class="cart-img">
                            <a href="{{item.product_obj.get_absolute_url}}"><img src="{{item.product_obj.main_cover.url}}" alt=""></a>
                        </div>
                        <div class="cart-title">
                            <h4><a href="{{item.product_obj.get_absolute_url}}">{{ item.product_obj.title}}</a></h4>
                            <span> {{ item.quantity }} × ${{ item.product_obj.total_price }}	</span>
                        </div>
                        <div class="cart-delete">
                            <a href="{% url 'cart:cart_remove' item.product_obj.id %}">×</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="cart-total">
                <h4>{% trans 'Subtotal' %}: <span>${{ cart.get_total_price }}</span></h4>
            </div>
            <div class="cart-checkout-btn">
                <a class="btn-hover cart-btn-style" href="{% url 'cart:cart_detail' %}">{% trans 'view cart' %}</a>
                <a class="no-mrg btn-hover cart-btn-style" href="{% url 'order:order' %}">{% trans 'checkout' %}</a>
            </div>
        </div>
    </div>
</div>

templates/inc/mobile_menu.html
{% load i18n %}
{% load static %}
<div class="sidebar-cart-active">
    <div class="sidebar-cart-all">
        <a class="cart-close" href="#"><i class="icon_close"></i></a>
        <div class="cart-content">
            <h3>Shopping Cart</h3>
            <ul>
                {% for item in cart %}
                    <li class="single-product-cart">
                        <div class="cart-img">
                            <a href="{{ item.product_obj.get_absolute_url }}"><img
                                    src="{{ item.product_obj.main_cover.url }}" alt=""></a>
                        </div>
                        <div class="cart-title">
                            <h4><a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a></h4>
                            <span> {{ item.quantity }} × ${{ item.product_obj.total_price }}	</span>
                        </div>
                        <div class="cart-delete">
                            <a href="{% url 'cart:cart_remove' item.product_obj.id %}">×</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="cart-total">
                <h4>{% translate 'Subtotal' %}: <span>${{ cart.get_total_price }}</span></h4>
            </div>
            <div class="cart-checkout-btn">
                <a class="btn-hover cart-btn-style" href="{% url 'cart:cart_detail' %}">{% trans 'view cart' %}</a>
                <a class="no-mrg btn-hover cart-btn-style" href="{% url 'order:order' %}">{% trans 'checkout' %}</a>
            </div>
        </div>
    </div>
</div>
<!-- Mobile menu start -->
<div class="mobile-header-active mobile-header-wrapper-style">
    <div class="clickalbe-sidebar-wrap">
        <a class="sidebar-close"><i class="icon_close"></i></a>
        <div class="mobile-header-content-area">
            <div class="header-offer-wrap-4 mobile-header-padding-border-4">
                <p class="black"><span class="uppercase">Free shipping</span> worldwide for orders over <span
                        class="amount">$159.</span> <a href="#">Learn More</a></p>
            </div>
            <div class="mobile-search mobile-header-padding-border-1">
                <form class="search-form" action="#">
                    <input type="text" placeholder="Search here…">
                    <button class="button-search"><i class="icon-magnifier"></i></button>
                </form>
            </div>
            <div class="mobile-menu-wrap mobile-header-padding-border-2">
                <!-- mobile menu start -->
                <nav>
                    <ul class="mobile-menu">
                        <li class="menu-item-has-children"><a href="index.html">Home</a>
                            <ul class="dropdown">
                                <li><a href="index.html">Home version 1 </a></li>
                                <li><a href="index-2.html">Home version 2</a></li>
                                <li><a href="index-3.html">Home version 3</a></li>
                                <li><a href="index-4.html">Home version 4</a></li>
                                <li><a href="index-5.html">Home version 5</a></li>
                                <li><a href="index-6.html">Home version 6</a></li>
                                <li><a href="index-7.html">Home version 7</a></li>
                                <li><a href="index-8.html">Home version 8</a></li>
                                <li><a href="index-9.html">Home version 9</a></li>
                                <li><a href="index-10.html">Home version 10</a></li>
                            </ul>
                        </li>
                        <li class="menu-item-has-children "><a href="#">shop</a>
                            <ul class="dropdown">
                                <li class="menu-item-has-children"><a href="#">shop layout</a>
                                    <ul class="dropdown">
                                        <li><a href="shop.html">standard style</a></li>
                                        <li><a href="shop-list.html">shop list style</a></li>
                                        <li><a href="shop-fullwide.html">shop fullwide</a></li>
                                        <li><a href="shop-no-sidebar.html">grid no sidebar</a></li>
                                        <li><a href="shop-list-no-sidebar.html">list no sidebar</a></li>
                                        <li><a href="shop-right-sidebar.html">shop right sidebar</a></li>
                                        <li><a href="store-location.html">store location</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-has-children"><a href="#">Products Layout</a>
                                    <ul class="dropdown">
                                        <li><a href="product-details.html">tab style 1</a></li>
                                        <li><a href="product-details-2.html">tab style 2</a></li>
                                        <li><a href="product-details-sticky.html">sticky style</a></li>
                                        <li><a href="product-details-gallery.html">gallery style </a></li>
                                        <li><a href="product-details-affiliate.html">affiliate style</a></li>
                                        <li><a href="product-details-group.html">group style</a></li>
                                        <li><a href="product-details-fixed-img.html">fixed image style </a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item-has-children"><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="about-us.html">about us </a></li>
                                <li><a href="cart.html">cart page</a></li>
                                <li><a href="checkout.html">checkout </a></li>
                                <li><a href="my-account.html">my account</a></li>
                                <li><a href="wishlist.html">wishlist </a></li>
                                <li><a href="compare.html">compare </a></li>
                                <li><a href="contact.html">contact us </a></li>
                                <li><a href="order-tracking.html">order tracking</a></li>
                                <li><a href="login-register.html">login / register </a></li>
                            </ul>
                        </li>
                        <li class="menu-item-has-children "><a href="#">Blog</a>
                            <ul class="dropdown">
                                <li><a href="blog.html">blog standard </a></li>
                                <li><a href="blog-no-sidebar.html">blog no sidebar </a></li>
                                <li><a href="blog-right-sidebar.html">blog right sidebar</a></li>
                                <li><a href="blog-details.html">blog details</a></li>
                            </ul>
                        </li>
                        <li><a href="contact.html">Contact us</a></li>
                    </ul>
                </nav>
                <!-- mobile menu end -->
            </div>
            <div class="mobile-social-icon">
                <a class="facebook" href="#"><i class="icon-social-facebook"></i></a>
                <a class="twitter" href="#"><i class="icon-social-twitter"></i></a>
                <a class="pinterest" href="#"><i class="icon-social-pinterest"></i></a>
                <a class="instagram" href="#"><i class="icon-social-instagram"></i></a>
            </div>
        </div>
    </div>
</div>